name: Release Drafter
tag-template: v$NEXT_MINOR_VERSION
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🛠 Maintenance'
    label: 'maintenance'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$REPOSITORY/compare/$PREVIOUS_TAG...$TAG
